### ISSUE TITLE
Futher Doc improvements

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#261]
From @deltaidea on #254:

- [ ] Performance tips: avoiding ambiguity, using moo. (#81, #238, #243, #250)
- [ ] Error handling:
    - [ ] List of possible exceptions. I imagine it's short, but I'm not sure about it myself.
    - [ ] Empty `parser.results`. (#253)
- [ ] Debugging tips: inspecting that the right tokens are parsed, using `nearley-test`. (#253)
- [ ] IDE support: syntax highlighting is supported at least in VS Code, probably in other editors too.
- [ ] Go through the source code and update references to the readme.

* @hardmath123: Introduction should also describe why people like nearley: it's user-friendly, easy to get started, works on both the browser and node, etc.
* @hardmath123: I think "parse complex data structures" is not quite what we wanted to say, even in the original README. This is a good opportunity to find better wording. Complex languages, perhaps?
* @tjvr: Document save() / restore()

**Comment by tjvr** [comment]
@Hardmath123

**Comment by Hardmath123** [comment]
Is .save() and .restore() even a thing anymore?

**Comment by tjvr** [comment]
> Is .save() and .restore() even a thing anymore?

Sure! `rewind()` is the thing that's deprecated.

**Comment by Hardmath123** [comment]
Okay, if you get a chance could you document .save() and .restore()? I think it should be a new section in the "using a parser" page. Importantly, it would be good to have some motivating examples for why you would use this feature.

**Comment by tjvr** [comment]
I wonder if we should be pushing lexers from the start, and move the syntax/explanation of scannerless parsing to a dedicated section...

**Comment by Hardmath123** [comment]
No, I think it's important for people to be able to get a parser working as fast as possible. We can mention lexers earlier, but the "getting started" and "home" pages should be scannerless, I think.

**Comment by diegoperini** [comment]
Are there good examples for `save()` and `restore()` anywhere outside of this repo, or maybe even here?

**Comment by tjvr** [comment]
@diegoperini That depends; what are you looking to do? 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by diegoperini** [comment]
I want to be able to recover from an invalid state to ignore error causing lines during the parse. I see no other way to detect multiple errors in a single source file. If there is a way, maybe `save()`/`restore()` is unnecessary, I really don't know. :)

**Comment by tjvr** [comment]
Perhaps looking at the tests would help? :man_shrugging: I'm sorry it's not documented better.

Save/restore was added in this commit:
https://github.com/kach/nearley/commit/b64ffe6bc3c0edef04defa7583c4c266f1bff069

The idea is that you call `save()` at a point that you want to be able to restore to later. If you want to be able to restore to _any_ token, then you should use the built-in `keepHistory` option.

You call `restore()` with the object that was returned from `save()`, or alternatively use `parser.table[index]` to restore to the parse state "at" index N (I think it's the parse state _after_ the Nth token).

The built-in `rewind(index)` method (which we might have removed since then) does this for you.

Hopefully that helps? :-)

**Comment by diegoperini** [comment]
It's good enough. Thank you so much. Maybe after I get a grasp of it, I can write the docs for you as my thanks.

**Comment by diegoperini** [comment]
@tjvr I saw something like `// TODO: moo save/restore` in the parser tests. Does this mean we cannot use `save()` and `restore()` if we use moo as a lexer?

**Comment by tjvr** [comment]
@diegoperini You should absolutely be able to use save() and restore() with Moo.
